### ISSUE TITLE
Search string pulls back all items regardless of whether there is a character match when using flat file

### ISSUE THREAD

**Issue by aoedipus** [tomik23/Leaflet.Autocomplete#4]

**Comment by aoedipus** [comment]
If "Foo Bar" is item 50 in a 200 item json flat file, and all prior items have no matching chars, they still get pulled into return list upon typing "Foo..." If the return list is constrained to 10, "Foo Bar" will never appear. This behavior is different than in all other examples, where the first chars pull back only items that contain matching chars. Is this intended?

**Comment by tomik23** [comment]
Hi, this library is changing quite dynamically ;) Are you working on the last version?
See [example](https://tomik23.github.io/autosuggest/) and [static file usage code](https://github.com/tomik23/autosuggest/blob/master/docs/index.html#L188)
Currently there is an **onSearch** function where you can move all logic and return only what is needed to be displayed.
