### ISSUE TITLE
Search for a polygon and insert a bar in the center of the map

### ISSUE THREAD

**Issue by Francesco2102** [tomik23/Leaflet.Autocomplete#9]
Hello,

how can I insert the "multi-layer-search" search bar in the center of the map?
Also I have entered some polygons in the search and I don't know how to find the center of the polygon.
Can you help me?

**Comment by tomik23** [comment]
Hi,

What does that mean in the "center of the page"? Do you want the search engine to be above the page? If so, it is enough to set position absolute for div.
As for finding the center of the range, use the plugin https://www.npmjs.com/package/@turf/centroid

This question probably doesn't apply to Leaflet.Autocomplete, only the basics of css and the ability to search for information on the Internet ;)

For the future, if you ask, please do it in the Discussions tab :)

Good luck.

**Comment by Francesco2102** [comment]
Thanks for the answer, for the 'multi-layer-search' search bar I want to move it on the map.
How can I do?

**Comment by tomik23** [comment]
In the first sentence there is a hint "position: absolute"

**Comment by Francesco2102** [comment]
ok, but to have the search bar on the map I have to create a button first?
as in this example: https://tomik23.github.io/leaflet-examples/#50.autocomplete-on-map

**Comment by tomik23** [comment]
I don't think we will get along like that;) It's best to draw what you would like a map with the search field and place it here.

**Comment by Francesco2102** [comment]
![sc_LI](https://user-images.githubusercontent.com/88318354/154087196-63b516a4-e922-4c21-89cc-330ad8376f44.jpg)


I didn't understand how to move the search bar on the map

**Comment by Francesco2102** [comment]
Yes

**Comment by Francesco2102** [comment]
Thanks
